#!/bin/bash
set -e

export HOME=/home/condensation

script_prefix=""

if [ -e /scripts/"$1" ]; then
  script_prefix="/scripts/"
fi

# If GOSU_USER environment variable set to something other than 0:0 (root:root),
# become user:group set within and exec command passed in args
if [ "$GOSU_USER" != "0:0" ]; then
    chown -R $GOSU_USER /home/condensation

    exec gosu $GOSU_USER env HOME=/home/condensation $script_prefix"$@"
fi

# If GOSU_USER was 0:0 exec command passed in args without gosu (assume already root)
exec $script_prefix"$@"
